### ISSUE TITLE
Error: Content Security Policy

### ISSUE THREAD

**Issue by javruben** [google/crx2app#1]
I followed the readme.txt and got to the yellow page. There I got:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
```

Any hints to what to do?

**Comment by johnjbarton** [comment]
Are you updated? I just fixed this Monday...

**Comment by javruben** [comment]
I just cloned master...

**Comment by johnjbarton** [comment]
Yes, a bug, just a sec

**Comment by johnjbarton** [comment]
Fixed by https://github.com/google/crx2app/commit/d5ca9c96f36143411d32ed7fc4f842a8698485ae

BTW I've switched to using web-sockets for connecting my Chrome devtools based project (qpp) to devtools, so I've not used this library recently.

**Comment by javruben** [comment]
Thanks for the fix and thanks for the hint. I'm just researching solutions for Cloud9. I understood that a plugin is needed to connect to Chrome to access the devtools from a web page (running in that same chrome). I know you can use web sockets, but that requires the user to start chrome with a flag. Could you clarify?

**Comment by javruben** [comment]
btw, qpp looks very interesting.

**Comment by javruben** [comment]
Now I can click "Add Allowed Site", but not yet "Save".

**Comment by johnjbarton** [comment]
crx2app can be used to connect a web page to the devtools back end, but it is not required.  The web-socket server for chrome devtools has improved and, with the increased importance of mobile, I think it would be the preferred solution for web-app development tools. 

The main advantages of crx2app: 
1. The communications never hits the IP network so in theory it is more secure,
2. The connection is within one browser so there are fewer options and failure modes.

Conversely, the advantages of web-sockets:
1. Communications over IP allows connection to mobile devices from desktop. (there are limitations on remote access).
2. Two different browsers can host the front and back end of devtools, allowing eg debugging of the debugger.

**Comment by javruben** [comment]
Thank you for this detailed description. I'm nearly convinced. I'll go that route first.

**Comment by johnjbarton** [comment]
If you follow the Remote Debug path on https://github.com/google/devtoolsExtended this should give you an example of web-socket use. I can help you with that over on that project.

I should be able to fix this bug tomorrow.
